id: PF99B11B6
initial_creation_type: ocr
source_metadata:
  volumes:
    8440645fa1154250bbbf01fd87a8a0eb:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ལུགས་ཀྱི་བསྟན་བཅོས་ཤེས་རབ་སྡོང་བུ།
      total_pages: 1872
      volume_number: 114
